# fly.toml app configuration file generated for silent-sea-9485 on 2023-08-24T11:29:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-sea-9485"
primary_region = "ams"

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "5001"
  DB_NAME = "lentDB"